### PR TITLE
Open Source Orgs Viz

### PR DESCRIPTION
**Pull request by nightwarrior-xxx**

### CODE REVIEW

**Comment by nightwarrior-xxx** [comment]
@tapaswenipathak PTAL

**Comment by nightwarrior-xxx** [comment]
https://drive.google.com/file/d/1pH4ofXQrG1UT-ydpGwKv3AWu0soFChrf/view?usp=sharing

**Comment by nightwarrior-xxx** [comment]
https://drive.google.com/file/d/1MASXtIdObRoB6X6WpeJyF2Wi0ZvJbbd5/view?usp=sharing

**Comment by nightwarrior-xxx** [comment]
@tapaswenipathak PTAL

**Comment by nightwarrior-xxx** [comment]
Fixes https://github.com/alice-sieve/Open-Source/issues/16

**Comment by nightwarrior-xxx** [comment]
@code-monk08 PTAL

**Comment by code-monk08** [comment]
Hey @nightwarrior-xxx I looked into your work, it seems good to me, there are chances of adding more features to the animation part itself, but maybe we can collaborate on that.

**Pull request closed without merging**
